plugins {
    id 'java'
    id "com.gradleup.shadow" version "9.4.1"
    id 'org.jetbrains.kotlin.jvm' version '2.4.0'
}

group = 'me.ybbbno'
version = '0.1'

repositories {
    mavenCentral()
    maven {
        name = "papermc-repo"
        url = "https://repo.papermc.io/repository/maven-public/"
    }

    maven {
        url = "https://repo.nexomc.com/releases"
    }
}

dependencies {
    compileOnly "io.papermc.paper:paper-api:1.21.11-R0.1-SNAPSHOT"
    compileOnly "com.nexomc:nexo:1.27.0"
    compileOnly "org.jetbrains.kotlin:kotlin-stdlib:2.4.20-RC2"
    implementation 'com.dropbox.core:dropbox-core-sdk:8.0.2'
    implementation files("libs/YBMJ-0.1.5.jar")
}

shadowJar {
    archiveClassifier.set('')

    exclude 'me/deadybbb/ybmj/paper-plugin.yml'

    relocate "me.deadybbb.YBMJ", "${project.group}"

    minimize()
}

def targetJavaVersion = 21
java {
    def javaVersion = JavaVersion.toVersion(targetJavaVersion)
    sourceCompatibility = javaVersion
    targetCompatibility = javaVersion
    if (JavaVersion.current() < javaVersion) {
        toolchain.languageVersion = JavaLanguageVersion.of(targetJavaVersion)
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'

    if (targetJavaVersion >= 10 || JavaVersion.current().isJava10Compatible()) {
        options.release.set(targetJavaVersion)
    }
}

processResources {
    def props = [version: version]
    inputs.properties props
    filteringCharset 'UTF-8'
    filesMatching('paper-plugin.yml') {
        expand props
    }
}
