name: NexoRPUploader
version: '0.1'
main: com.sunphantom.nexorpuploader.NexoRPUploader
api-version: '1.21'
authors: [ ybbbno ]
dependencies:
  server:
    Nexo:
      required: true
      load: BEFORE